kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: kafka-demosandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32430
    nodePort: 32430
  type: NodePort
