kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: kafka-qasandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32440
    nodePort: 32440
  type: NodePort
