kind: Service
apiVersion: v1
metadata:
  name: outside-2
  namespace: kafka-uatsandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "2"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32422
    nodePort: 32422
  type: NodePort
