kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: kafka-uatsandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32420
    nodePort: 32420
  type: NodePort
