kind: Service
apiVersion: v1
metadata:
  name: outside-1
  namespace: kafka-apisandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "1"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32411
    nodePort: 32411
  type: NodePort