kind: Service
apiVersion: v1
metadata:
  name: outside-1
  namespace: kafka-production
spec:
  selector:
    app: kafka
    kafka-broker-id: "1"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32501
    nodePort: 32501
  type: NodePort