kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: kafka-apisandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32410
    nodePort: 32410
  type: NodePort