kind: Service
apiVersion: v1
metadata:
  name: outside-1
  namespace: kafka-tstsandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "1"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32451
    nodePort: 32451
  type: NodePort
