kind: Service
apiVersion: v1
metadata:
  name: outside-1
  namespace: kafka-uatsandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "1"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32421
    nodePort: 32421
  type: NodePort
