kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: kafka-production
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32500
    nodePort: 32500
  type: NodePort