kind: Service
apiVersion: v1
metadata:
  name: outside-2
  namespace: kafka-production
spec:
  selector:
    app: kafka
    kafka-broker-id: "2"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32502
    nodePort: 32502
  type: NodePort