kind: Service
apiVersion: v1
metadata:
  name: outside-2
  namespace: kafka-tstsandbox
spec:
  selector:
    app: kafka
    kafka-broker-id: "2"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32452
    nodePort: 32452
  type: NodePort
